### PR TITLE
Link to CUDA.jl 5.0 blog post.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Looks like the RSS feed doesn't include links to external entries. Will need to fix that.

**Comment by maleadt** [comment]
@tlienart is there a way for the external entries (i.e. posts that just link to another URL, as added in this PR) to show up in the RSS feed? IIRC, that's why with Hugo I used to have actual posts for external entries, but with a special tag `redirect = "http://..."` that generated a `meta http-equiv="Refresh"` header,  instead of adding a special `external_entries` to the index like you did when porting our Hugo website to Franklin.jl (also because RSS entries need additional information, like the author, etc).

**Comment by maleadt** [comment]
@tlienart Friendly ping; happy to take a look myself if you could give me some pointers 🙂

**Comment by tlienart** [comment]
so there's this `Franklin.RSS_ITEMS` list which you could push to in a hfun, elements of it are `Franklin.RSSItem` with fields

```
item::String
date::Date
tags::Vector{String} # <-- in your case empty
```

so you could have a hfun called from `post/index.md` which pushes these external entries to it. This will get picked up and sorted by `rss_generator()` afterwards. the `add_rss_item` which generates these elements for posts with rss stuff in it should be useful too: https://github.com/tlienart/Franklin.jl/blob/5b82e05d1aaf7f54957aeeaa04a2683326205daf/src/manager/rss_generator.jl#L133-L151

I'd suggest using this and then if you think it'd be nice to have an actual clean pattern for this in Franklin, open an issue there? I'm just a bit slow at opening new features there as I'd first like to make a new release (I've been wanting to do that for a very long time and am struggling to push it over the line due to time constraints..)

**Comment by maleadt** [comment]
Thanks for the suggestion. I'd really to avoid further special-casing in `index.md` though. Isn't it possible to re-use the existing functionality for emitting RSS entries, i.e., by creating an actual post, and redirecting to the external entry? If it's too hard to do that 'properly' (by emitting a `meta http-equiv="Refresh"` header tag), some inline Javascript should be able to redirect as well. Is it possible to use inline HTML/Javascript in a post to do so?

EDIT: I'll try with a custom `hfun`. But emitting a `meta` header would be better.

**Comment by tlienart** [comment]
Yeah I understand, was just trying to give you a quick way out given I can't currently commit time to a nicer solution.

A note that `{{redirect ...}}` is already defined (your definition will take over so that's fine if it works for you), see https://franklinjl.org/syntax/page-variables/index.html#basic_functions

glad that you figured out an acceptable path for now

**Pull request merged**
