### PR TITLE
Update ROCm doc

### PR DESCRIPTION
**Pull request by luraess**
This PR updates the ROCm doc to match the style and content of the CUDA page from the website, namely:
- update content
- add preliminary perf comparison between AMDGPU and HIP C++ for two simple kernels

### CODE REVIEW

**Comment by luraess** [comment]
@pxl-th you may want to verify the content as well.

**Comment by pxl-th** [comment]
Looks good to me! Thanks!

**Comment by maleadt** [comment]
Did you try this change locally?

image

**Comment by luraess** [comment]
The html `~~` are missing. Fixing this now.

**Comment by luraess** [comment]
@maleadt #37 fixes it.

**Pull request merged**
